### ISSUE TITLE
DNSCRYPT_LISTEN_PORT in the container healtcheck versus the actual listen port

### ISSUE THREAD

**Issue by larssb** [djaydev/docker-dnscrypt-proxy#1]
**ISSUE**

If one chooses to change the `DNSCRYPT_LISTEN_PORT` via an environment variable to the `Docker` container on startup. This port will not be reflected in the `Docker` container health check, where the `drill` cmd is used for checking the state of the container.

This results in: `djaydev/dnscrypt-proxy  "/entrypoint.sh"  11 days ago  Up 4 hours (unhealthy)                            dnscrypt-proxy` as can be seen when executing: `docker ps`

More serious though, is the fact that a lot of "old" `drill` cmds seems to be hanging around. Causing an issue on the host (I run the container in `network_mode=host`) in regards to resource exhaustion. Specifically this error: `fork: Resource temporarily unavailable`. Which I'm not a 100% is being caused by this issue, but I think this smells.

See this `top` cmd output.

```
12529     0 root     S     1576   0%   3   0% /bin/sh -c drill -p $DNSCRYPT_LISTEN_PORT cloudflare.com @127.0.0.1 || exit 1
   67     1 root     Z        0   0%   0   0% [drill]
   60     1 root     Z        0   0%   2   0% [drill]
   74     1 root     Z        0   0%   3   0% [drill]
   89     1 root     Z        0   0%   3   0% [drill]
   97     1 root     Z        0   0%   1   0% [drill]
  104     1 root     Z        0   0%   3   0% [drill]
  110     1 root     Z        0   0%   3   0% [drill]
  117     1 root     Z        0   0%   3   0% [drill]
   47     1 root     Z        0   0%   3   0% [drill]
  131     1 root     Z        0   0%   2   0% [drill]
  138     1 root     Z        0   0%   2   0% [drill]
  145     1 root     Z        0   0%   0   0% [drill]
  152     1 root     Z        0   0%   1   0% [drill]
  159     1 root     Z        0   0%   0   0% [drill]
  166     1 root     Z        0   0%   0   0% [drill]
  173     1 root     Z        0   0%   2   0% [drill]
  180     1 root     Z        0   0%   2   0% [drill]
  189     1 root     Z        0   0%   3   0% [drill]
   32     1 root     Z        0   0%   1   0% [drill]
  203     1 root     Z        0   0%   2   0% [drill]
  209     1 root     Z        0   0%   1   0% [drill]
  216     1 root     Z        0   0%   0   0% [drill]
  223     1 root     Z        0   0%   1   0% [drill]
  230     1 root     Z        0   0%   0   0% [drill]
  237     1 root     Z        0   0%   2   0% [drill]
  244     1 root     Z        0   0%   0   0% [drill]
  251     1 root     Z        0   0%   3   0% [drill]
  258     1 root     Z        0   0%   0   0% [drill]
  265     1 root     Z        0   0%   1   0% [drill]
  272     1 root     Z        0   0%   1   0% [drill]
  279     1 root     Z        0   0%   2   0% [drill]
  286     1 root     Z        0   0%   0   0% [drill]
  292     1 root     Z        0   0%   0   0% [drill]
  299     1 root     Z        0   0%   2   0% [drill]
   40     1 root     Z        0   0%   3   0% [drill]
  313     1 root     Z        0   0%   1   0% [drill]
  321     1 root     Z        0   0%   3   0% [drill]
  328     1 root     Z        0   0%   1   0% [drill]
  335     1 root     Z        0   0%   1   0% [drill]
  342     1 root     Z        0   0%   3   0% [drill]
  349     1 root     Z        0   0%   0   0% [drill]
```

**TROUBLESHOOTING**

1. Executed: `top` inside the container and this is the result

```txt
12098     1 root     S     3704   0%   1   0% drill -p 5353 cloudflare.com @127.0.0.1
12105     1 root     S     3704   0%   2   0% drill -p 5353 cloudflare.com @127.0.0.1
```

As it can be seen port *5353* is used no matter what one might have set it to in the `dnscrypt-proxy.toml` file. Which has the following value:

```txt
## List of local addresses and ports to listen to. Can be IPv4 and/or IPv6.
listen_addresses = ['0.0.0.0:5354']
```

**EXPECTATION**

The `drill` cmd in the container health check should use the correct port, a reflection of what was being set as the `DNSCRYPT_LISTEN_PORT` on container startup

**Comment by djaydev** [comment]
The default port is 5053 from the dockerfile `DNSCRYPT_LISTEN_PORT=5053` I'm not sure how it's showing 5353 for you.  

When I run top from the container I don't see the drill command, but I'm using the 5053
```
Mem: 55050148K used, 10935436K free, 2852192K shrd, 7989356K buff, 40507348K cached
CPU:   2% usr   0% sys   0% nic  96% idle   0% io   0% irq   0% sirq
Load average: 0.49 0.72 0.62 2/1638 30578
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    1     0 dnscrypt S     120m   0%   6   0% dnscrypt-proxy -config /usr/share/dnscrypt-proxy/example-dnscrypt-proxy.toml
30567     0 root     S     1648   0%   4   0% sh
30572 30567 root     R     1584   0%   8   0% top
```

I just kind of put this container together quickly to satisfy a personal need. I'm not a developer or anything I have no clue how to fix that. 

Please check out https://github.com/vgist/dockerfiles/tree/master/dnscrypt or https://github.com/klutchell/dnscrypt-proxy for a better maintained dnscrypt-proxy docker.

**Comment by larssb** [comment]
Hi @djaydev,

Thank you for replying so quickly. I just did some more troubleshooting and I can conclude that it was me mixing "things" that should not be mixed.

I'm volume mapping a locally configured `dnscrypt-proxy.toml` file into the `dnscrypt-proxy` container. So what I was doing was actually setting the `dnscrypt-proxy` listening port in an environment variable and then also in the `dnscrypt-proxy.toml` file. Not good 👎  ... so the environment variable is actually picked up as it should, by the health check command. Hence the variable reference.

When executing `top` I now only have one `drill` process going. So things are good!

Thank you for spending the time on it. And for the reference to the better maintained `dnscrypt-proxy` images. However, as long as you upgrade to newer `dnscrypt-proxy` releases, I might as well go with yours now.

Have a great day/night
